language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install coveralls pep8 pylint nose sympy
# matrix:
#   include:
#   - env: COMMAND=pylint
#     python: 3.5
#     script: pylint -f parseable -d I0011,R0801 rpn tests
#     after_success: true
#   - env: COMMAND=pep8
#     python: 3.5
#     script: pep8 rpn tests
#     after_success: true
script:
  - nosetests
after_success:
    - coveralls